version: '3.8'
services:
  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - DB_DIALECT=sqlite
      - JWT_SECRET=ChangeThisSecret
      - JWT_EXPIRES_IN=1h
    ports:
      - '4000:4000'

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=http://backend:4000/api/v1
    ports:
      - '5173:5173'
    depends_on:
      - backend
